version: '3.8'

services:
  frontend:
    container_name: myreact
    build:
      context: ./frontend
    image: shivarna1/three-tier-crud-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network


  backend:
    container_name: mybackend
    build:
      context: ./backend  
    image: shivarna1/three-tier-crud-backend:latest
    ports:
      - "5000:5000"  # Expose .NET API port
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=testdb;Username=postgres;Password=root
    depends_on:
      - postgres
    networks:
      - app-network


  postgres:
    container_name: mypostgres
    image: postgres:latest  # Specify the PostgreSQL version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql  # Mount the SQL script
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

