version: '3.9'

services:
  mypostgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - app_network

  mydotnet:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mydotnet
    ports:
      - "9080:9080"
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__ApiDatabase: ${CONNECTION_STRING}
    depends_on:
      - mypostgres
    networks:
      - app_network

  myreact:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myreact
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    depends_on:
      - mydotnet
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:

