apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=           # base64 encoded "postgres"
  POSTGRES_PASSWORD: cm9vdA==           # base64 encoded "root"
  POSTGRES_DB: dGVzdGRi                 # base64 encoded "testdb"


