apiVersion: v1
kind: Service
metadata:
  labels:
    app: mypostgres
  name: mypostgres
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: mypostgres
