apiVersion: v1
kind: Service
metadata:
  name: myreact
  labels:
    app: myreact
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000 # You can modify this as needed
  selector:
    app: myreact

